# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 288713ae017a6c41d987e44c85f14ceb36717d074a4f55ba80a825fb0147fbf686a17f963167decb3b536bd0b163cf5f72200e0676ec29ed89f55c9dbeac840e

test:
  secret_key_base: a5f2a6693fea9396b052befd977393fc0a8e1f329d5708d007af62ef56436ba74e33b1360d48353b204132f0cb85d4ef72d3fbb39ebed428a7459fd5025d49ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
